#479 Add 0.8.0 workflow example
eclipse-glsp/glsp-examples pull request #86
Opened 2021-12-16 13:12 UTC by tortmayr

- Add the sources for the 0.8.0 workflow example
- Improve example structure
- Add a vscode workspace file for each example
- Add support of the Java code in Vscode

Fixex eclipse-glsp/glsp/issues/479

2022-02-08 17:42 UTC, ndoschek requested changes
Thanks Tobias looks good to me overall!
There are some minor issues with the VSCode tasks, I added some suggestions inline.

- The workflow example is not consuming the new styling yet, will we update the workflow example to 0.9.0 in a follow-up?
- Regarding the file headers of the changed files, we should update them to `Copyright (c) 20xx-2022 ...`

2022-02-08 17:42 UTC, ndoschek commented on minimal/glsp-server/.vscode/tasks.json
> +      "command": "yarn ",
This is fixed with https://github.com/eclipse-glsp/glsp-examples/pull/89, but for the sake of completeness:
```suggestion
      "command": "mvn clean verify",
```

2022-02-08 17:42 UTC, ndoschek commented on workflow/glsp-server/.vscode/tasks.json
> +      "command": "yarn ",
```suggestion
      "command": "mvn clean verify",
```

2022-02-08 17:42 UTC, ndoschek commented on minimal/glsp-client/package.json
> +    "start:external": "yarn rebuild:browser && --cwd minimal-browser-app start:external"
This is fixed with https://github.com/eclipse-glsp/glsp-examples/pull/89, but for the sake of completeness:
```suggestion
    "start:external": "yarn rebuild:browser && yarn --cwd minimal-browser-app start:external"
```

2022-02-08 17:42 UTC, ndoschek commented on workflow/glsp-client/package.json
> +    "start:external": "yarn rebuild:browser && --cwd workflow-browser-app start:external"
```suggestion
    "start:external": "yarn rebuild:browser && yarn --cwd workflow-browser-app start:external"
```

2022-02-08 17:42 UTC, ndoschek commented on workflow/glsp-client/workflow-browser-app/package.json
> +    "start:debug": "theia start --WF_GLSP=5007  --root-dir=../workspace --loglevel=debug",
This should be named `start:external` to align with the task call (and the minimal example). 
```suggestion
    "start:external": "theia start --WF_GLSP=5007 --root-dir=../workspace --DEBUG",
```

2022-02-08 21:56 UTC, tortmayr commented
> The workflow example is not consuming the new styling yet, will we update the workflow example to 0.9.0 in a follow-up?

It will be updated to 0.9.0 in a follow-up. I'm working on it right now. However, 0.9.0 also does not contain the new styling. The new styling is currently only part of the nightly releases (next). We will have to wait for the 0.10.0 release to consume it here. (This example repository is intended to stay on the latest release and not any nightly versions).

> Regarding the file headers of the changed files, we should update them to Copyright (c) 20xx-2022 ...
I guess so, I wil take care of it

2022-02-09 08:44 UTC, ndoschek approved these changes
Thanks a lot for the quick update Tobias! LGTM :+1:

2022-02-09 09:40 UTC, merged